Parameters:
  KeyPairName:
    Type: String
    Description: 'Enter the name of the key (.pem) for SSH access to EC2 instances.'
  InstanceType:
    Type: String
    Default: t2.large
    AllowedValues:
      - t2.micro
      - t2.medium
      - t2.large
      - t2.2xlarge
    Description: 'Select instance size.'
  InstanceAMI:
    Type: String
    Default: ami-02541b8af977f6cdd
    Description: 'AMI will vary based on region. This template assumes US-WEST-1 region. Adjust accordingly to your region.' 

Resources:
  ApplicationSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow traffic from everywhere
      SecurityGroupIngress:
        IpProtocol: -1
        CidrIp: 0.0.0.0/0
  DatabaseSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow traffic from everywhere
      SecurityGroupIngress:
        IpProtocol: -1
        CidrIp: 0.0.0.0/0
  Mongo:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: 
        Ref: InstanceAMI
      InstanceType:
        Ref: InstanceType
      SecurityGroupIds: 
        - !Ref DatabaseSG
      KeyName: !Ref KeyPairName
      Tags:
        - Key: "Name"
          Value: MongoDB
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe

          # PRE-REQUISITES
          #--------------------------#
          yum update -y
          #-------------------------------------------------------------------------------------------------#

          # installing mongoDB 4.4 
          #--------------------------#
          cat > /etc/yum.repos.d/mongodb-org-4.4.repo <<EOF
          [mongodb-org-4.4]
          name=MongoDB Repository
          baseurl=https://repo.mongodb.org/yum/amazon/2/mongodb-org/4.4/x86_64/
          gpgcheck=1
          enabled=1
          gpgkey=https://www.mongodb.org/static/pgp/server-4.4.asc
          EOF

          yum install mongodb-org -y

          #NOTE: Let's make this less error-prone, line 29 will change depending on mongodb version
          sudo sed -i '29s/.*/  bindIp: 0.0.0.0/' /etc/mongod.conf 

          sudo systemctl start mongod
          sudo systemctl enable mongod
          #-------------------------------------------------------------------------------------------------#

  Redis:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: 
        Ref: InstanceAMI
      InstanceType:
        Ref: InstanceType
      SecurityGroupIds: 
        - !Ref DatabaseSG
      KeyName: !Ref KeyPairName
      Tags:
        - Key: "Name"
          Value: Redis
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          
          # PRE-REQUISITES
          #--------------------------#
          yum update -y
          yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm -y
          yum install python34 -y
          yum install pygpgme yum-utils wget -y
          yum install httpd-tools -y
          
          # installing Redis 
          #--------------------------#
          yum install redis -y

          #NOTE: Let's make this less error-prone, line 61 will change depending on redis version
          sudo sed -i '61s/.*/bind 0.0.0.0/' /etc/redis.conf

          sudo systemctl start redis
          sudo systemctl enable redis
          #-------------------------------------------------------------------------------------------------#


  Pump:
    Type: AWS::EC2::Instance
    DependsOn: 
      - Mongo
      - Redis
    Properties:
      ImageId: 
        Ref: InstanceAMI
      InstanceType:
        Ref: InstanceType
      SecurityGroupIds: 
        - !Ref ApplicationSG
      KeyName: !Ref KeyPairName
      Tags:
        - Key: "Name"
          Value: Tyk Pump
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          
          # PRE-REQUISITES
          #--------------------------#
          yum update -y
          yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm -y
          yum install python34 -y
          yum install pygpgme yum-utils wget -y
          #-------------------------------------------------------------------------------------------------#

          # installing TYK PUMP 
          #--------------------------#
          cat > /etc/yum.repos.d/tyk_tyk-pump.repo <<EOF
          [tyk_tyk-pump]
          name=tyk_tyk-pump
          baseurl=https://packagecloud.io/tyk/tyk-pump/el/7/\$basearch
          repo_gpgcheck=1
          gpgcheck=1
          enabled=1
          gpgkey=https://keyserver.tyk.io/tyk.io.rpm.signing.key.2020
                 https://packagecloud.io/tyk/tyk-pump/gpgkey
          sslverify=1
          sslcacert=/etc/pki/tls/certs/ca-bundle.crt
          metadata_expire=300
          EOF

          yum -q makecache -y --disablerepo='*' --enablerepo='tyk_tyk-pump'

          yum install tyk-pump -y

          /opt/tyk-pump/install/setup.sh \
          --redishost=${Redis.PublicIp} \
          --redisport=6379 \
          --mongo=mongodb://${Mongo.PublicIp}/tyk_analytics 1> /home/ec2-user/pump.txt

          sudo systemctl start tyk-pump
          sudo systemctl enable tyk-pump
          #-------------------------------------------------------------------------------------------------#

  Gateway:
    Type: AWS::EC2::Instance
    DependsOn: 
      - Redis
    Properties:
      ImageId: 
        Ref: InstanceAMI
      InstanceType:
        Ref: InstanceType
      SecurityGroupIds: 
        - !Ref ApplicationSG
      KeyName: !Ref KeyPairName
      Tags:
        - Key: "Name"
          Value: Tyk Gateway
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe

          # PRE-REQUISITES
          #--------------------------#
          yum update -y
          yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm -y
          yum install python34 -y
          yum install pygpgme yum-utils wget -y
          #-------------------------------------------------------------------------------------------------#
          
          # installing TYK GATEWAY 
          #--------------------------#
          cat > /etc/yum.repos.d/tyk_tyk-gateway.repo <<EOF
          [tyk_tyk-gateway]
          name=tyk_tyk-gateway
          baseurl=https://packagecloud.io/tyk/tyk-gateway/el/7/\$basearch
          repo_gpgcheck=1
          gpgcheck=1
          enabled=1
          gpgkey=https://keyserver.tyk.io/tyk.io.rpm.signing.key.2020
                 https://packagecloud.io/tyk/tyk-gateway/gpgkey
          sslverify=1
          sslcacert=/etc/pki/tls/certs/ca-bundle.crt
          metadata_expire=300
          EOF

          yum -q makecache -y --disablerepo='*' --enablerepo='tyk_tyk-gateway' --enablerepo=epel

          yum install tyk-gateway -y

          /opt/tyk-gateway/install/setup.sh \
          --dashboard=1 \
          --listenport=8080 \
          --redishost=${Redis.PublicIp} \
          --redisport=6379 1> /home/ec2-user/gateway.txt

          sudo systemctl start tyk-gateway
          sudo systemctl enable tyk-gateway
          #-------------------------------------------------------------------------------------------------#

  Dashboard:
    Type: AWS::EC2::Instance
    DependsOn: 
      - Mongo
      - Redis
      - Gateway
    Properties:
      ImageId: 
        Ref: InstanceAMI
      InstanceType:
        Ref: InstanceType
      SecurityGroupIds: 
        - !Ref ApplicationSG
      KeyName: !Ref KeyPairName
      Tags:
        - Key: "Name"
          Value: Tyk Dashboard
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe

          # PRE-REQUISITES
          #--------------------------#
          yum update -y
          yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm -y
          yum install python34 -y
          yum install pygpgme yum-utils wget -y
          #-------------------------------------------------------------------------------------------------#

          # installing TYK DASHBOARD 
          #--------------------------#
          cat > /etc/yum.repos.d/tyk_tyk-dashboard.repo <<EOF
          [tyk_tyk-dashboard]
          name=tyk_tyk-dashboard
          baseurl=https://packagecloud.io/tyk/tyk-dashboard/el/7/\$basearch
          repo_gpgcheck=1
          gpgcheck=1
          enabled=1
          gpgkey=https://keyserver.tyk.io/tyk.io.rpm.signing.key.2020
                 https://packagecloud.io/tyk/tyk-dashboard/gpgkey
          sslverify=1
          sslcacert=/etc/pki/tls/certs/ca-bundle.crt
          metadata_expire=300
          EOF

          yum -q makecache -y --disablerepo='*' --enablerepo='tyk_tyk-dashboard'

          yum install tyk-dashboard -y

          dash=$(curl http://169.254.169.254/latest/meta-data/public-ipv4 -s)

          /opt/tyk-dashboard/install/setup.sh \
          --listenport=3000 \
          --redishost=${Redis.PublicIp} \
          --redisport=6379 \
          --mongo=mongodb://${Mongo.PublicIp}/tyk_analytics \
          --tyk_api_hostname=${Gateway.PublicIp}:8080 \
          --tyk_node_hostname=http://${Gateway.PublicIp} \
          --tyk_node_port=8080 \
          --portal_root=/portal \
          --domain="$dash" 1> /home/ec2-user/dashboard.txt

          sudo systemctl start tyk-dashboard
          sudo systemctl enable tyk-dashboard
          #-------------------------------------------------------------------------------------------------#
