AWSTemplateFormatVersion: 2010-09-09

Parameters:
  VpcName:
    Description: "Enter VPC ID"
    Type: String
  KeyPairName:
    Type: String

Resources:
  ApplicationSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow traffic from everywhere
      SecurityGroupIngress:
        IpProtocol: -1
        CidrIp: 0.0.0.0/0
  DatabaseSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow traffic from everywhere
      SecurityGroupIngress:
        IpProtocol: -1
        CidrIp: 0.0.0.0/0
  Mongo:
    Type: AWS::EC2::Instance
    Properties:
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe

          yum update -y
          
          cat > /etc/yum.repos.d/mongodb-org-4.4.repo <<EOF
          [mongodb-org-4.4]
          name=MongoDB Repository
          baseurl=https://repo.mongodb.org/yum/amazon/2/mongodb-org/4.4/x86_64/
          gpgcheck=1
          enabled=1
          gpgkey=https://www.mongodb.org/static/pgp/server-4.4.asc
          EOF
          
          yum install mongodb-org -y

          sed -i '29s/.*/  bindIp: 0.0.0.0/' /etc/mongod.conf

          systemctl start mongod

      ImageId: ami-0ba0ce0c11eb723a1
      InstanceType: t2.micro
      SecurityGroupIds: 
        - !Ref DatabaseSG
      KeyName: !Ref KeyPairName
      Tags:
        - Key: "Name"
          Value: mongoDB

  Redis:
    Type: AWS::EC2::Instance
    Properties:
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe

          yum update -y
          yum install make gcc tcl wget -y
          yum groupinstall 'Development Tools' -y
          
          #THIS SECTION IS FOR REDIS 6
          wget https://download.redis.io/releases/redis-6.0.14.tar.gz -P /home/ec2-user/
          tar xzf /home/ec2-user/redis-6.0.14.tar.gz -C /home/ec2-user/
          cd /home/ec2-user/redis-6.0.14
          make MALLOC=libc > /home/ec2-user/malloc_logs.txt
          sed -i '69s/.*/bind 0.0.0.0/' /home/ec2-user/redis-6.0.14/redis.conf
          cp /home/ec2-user/redis-6.0.14/src/redis-server /usr/local/bin/
          cp /home/ec2-user/redis-6.0.14/src/redis-cli /usr/local/bin/
          /home/ec2-user/redis-6.0.14/src/redis-server /home/ec2-user/redis-6.0.14/redis.conf

          #THIS SECTION IS FOR REDIS 5 - reaching EOL October 31. 2021
          #wget https://download.redis.io/releases/redis-5.0.10.tar.gz -P /home/ec2-user/
          #tar xzf /home/ec2-user/redis-5.0.10.tar.gz -C /home/ec2-user/
          #cd /home/ec2-user/redis-5.0.10
          #make MALLOC=libc > /home/ec2-user/malloc_logs.txt
          #sed -i '69s/.*/bind 0.0.0.0/' /home/ec2-user/redis-5.0.10/redis.conf
          #cp /home/ec2-user/redis-5.0.10/src/redis-server /usr/local/bin/
          #cp /home/ec2-user/redis-5.0.10/src/redis-cli /usr/local/bin/
          #/home/ec2-user/redis-5.0.10/src/redis-server /home/ec2-user/redis-5.0.10/redis.conf

      ImageId: ami-0ba0ce0c11eb723a1
      InstanceType: t2.micro
      SecurityGroupIds: 
        - !Ref DatabaseSG
      KeyName: !Ref KeyPairName
      Tags:
        - Key: "Name"
          Value: redis
  
  Dashboard:
    Type: AWS::EC2::Instance
    DependsOn: 
      - Mongo
      - Redis
      - Gateway
    Properties:
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe

          yum update -y
          yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm -y
          yum install python34 -y
          yum install pygpgme yum-utils wget -y

          cat > /etc/yum.repos.d/tyk_tyk-dashboard.repo <<EOF
          [tyk_tyk-dashboard]
          name=tyk_tyk-dashboard
          baseurl=https://packagecloud.io/tyk/tyk-dashboard/el/7/\$basearch
          repo_gpgcheck=1
          gpgcheck=1
          enabled=1
          gpgkey=https://keyserver.tyk.io/tyk.io.rpm.signing.key.2020
                 https://packagecloud.io/tyk/tyk-dashboard/gpgkey
          sslverify=1
          sslcacert=/etc/pki/tls/certs/ca-bundle.crt
          metadata_expire=300
          EOF

          yum -q makecache -y --disablerepo='*' --enablerepo='tyk_tyk-dashboard'

          #To install latest version from packagecloud
          yum install tyk-dashboard -y
          
          #To install specific version from package cloud
          #yum install tyk-dashboard-3.0.1-1.x86_64 -y

          dash=$(curl http://169.254.169.254/latest/meta-data/public-ipv4 -s)

          /opt/tyk-dashboard/install/setup.sh \
          --listenport=3000 \
          --redishost=${Redis.PublicIp} \
          --redisport=6379 \
          --mongo=mongodb://${Mongo.PublicIp}/tyk_analytics \
          --tyk_api_hostname=${Gateway.PublicIp}:8080 \
          --tyk_node_hostname=http://${Gateway.PublicIp} \
          --tyk_node_port=8080 \
          --portal_root=/portal \
          --domain="$dash"

          service tyk-dashboard start

      ImageId: ami-0ba0ce0c11eb723a1
      InstanceType: t2.micro
      SecurityGroupIds: 
        - !Ref ApplicationSG
      KeyName: !Ref KeyPairName
      Tags:
        - Key: "Name"     

  Pump:
    Type: AWS::EC2::Instance
    DependsOn: 
      - Mongo
      - Redis
    Properties:
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe

          yum update -y
          yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm -y
          yum install python34 -y
          yum install pygpgme yum-utils wget -y

          cat > /etc/yum.repos.d/tyk_tyk-pump.repo <<EOF
          [tyk_tyk-pump]
          name=tyk_tyk-pump
          baseurl=https://packagecloud.io/tyk/tyk-pump/el/7/\$basearch
          repo_gpgcheck=1
          gpgcheck=1
          enabled=1
          gpgkey=https://keyserver.tyk.io/tyk.io.rpm.signing.key.2020
                 https://packagecloud.io/tyk/tyk-pump/gpgkey
          sslverify=1
          sslcacert=/etc/pki/tls/certs/ca-bundle.crt
          metadata_expire=300
          EOF

          yum -q makecache -y --disablerepo='*' --enablerepo='tyk_tyk-pump'

          
          #To install latest version from packagecloud
          yum install tyk-pump -y
          
          #To install specific version from packagecloud
          #yum install tyk-pump-1.0.1-1.x86_64 -y

          /opt/tyk-pump/install/setup.sh \
          --redishost=${Redis.PublicIp} \
          --redisport=6379 \
          --mongo=mongodb://${Mongo.PublicIp}/tyk_analytics

          service tyk-pump start

      ImageId: ami-0ba0ce0c11eb723a1
      InstanceType: t2.micro
      SecurityGroupIds: 
        - !Ref ApplicationSG
      KeyName: !Ref KeyPairName
      Tags:
        - Key: "Name"
          Value: Pump     

  Gateway01:
    Type: AWS::EC2::Instance
    DependsOn: 
      - Redis
    Properties:
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe

          yum update -y
          yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm -y
          yum install python34 -y
          yum install pygpgme yum-utils wget -y
          
          cat > /etc/yum.repos.d/tyk_tyk-gateway.repo <<EOF
          [tyk_tyk-gateway]
          name=tyk_tyk-gateway
          baseurl=https://packagecloud.io/tyk/tyk-gateway/el/7/\$basearch
          repo_gpgcheck=1
          gpgcheck=1
          enabled=1
          gpgkey=https://keyserver.tyk.io/tyk.io.rpm.signing.key.2020
                 https://packagecloud.io/tyk/tyk-gateway/gpgkey
          sslverify=1
          sslcacert=/etc/pki/tls/certs/ca-bundle.crt
          metadata_expire=300
          EOF

          yum -q makecache -y --disablerepo='*' --enablerepo='tyk_tyk-gateway' --enablerepo=epel

          #To install latest version from packagecloud 
          yum install tyk-gateway -y
          
          #To install specific version from packagecloud 
          #yum install tyk-gateway-3.0.1-1.x86_64 -y
         

          /opt/tyk-gateway/install/setup.sh \
          --dashboard=1 \
          --listenport=8080 \
          --redishost=${Redis.PublicIp} \
          --redisport=6379

          service tyk-gateway start

      ImageId: ami-0ba0ce0c11eb723a1
      InstanceType: t2.micro
      SecurityGroupIds: 
        - !Ref ApplicationSG
      KeyName: !Ref KeyPairName
      Tags:
        - Key: "Name"
          Value: Gateway01 

  Gateway02:
    Type: AWS::EC2::Instance
    DependsOn: 
      - Redis
    Properties:
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe

          yum update -y
          yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm -y
          yum install python34 -y
          yum install pygpgme yum-utils wget -y
          
          cat > /etc/yum.repos.d/tyk_tyk-gateway.repo <<EOF
          [tyk_tyk-gateway]
          name=tyk_tyk-gateway
          baseurl=https://packagecloud.io/tyk/tyk-gateway/el/7/\$basearch
          repo_gpgcheck=1
          gpgcheck=1
          enabled=1
          gpgkey=https://keyserver.tyk.io/tyk.io.rpm.signing.key.2020
                 https://packagecloud.io/tyk/tyk-gateway/gpgkey
          sslverify=1
          sslcacert=/etc/pki/tls/certs/ca-bundle.crt
          metadata_expire=300
          EOF

          yum -q makecache -y --disablerepo='*' --enablerepo='tyk_tyk-gateway' --enablerepo=epel

          #To install latest version from packagecloud 
          yum install tyk-gateway -y
          
          #To install specific version from packagecloud 
          #yum install tyk-gateway-3.0.1-1.x86_64 -y
         

          /opt/tyk-gateway/install/setup.sh \
          --dashboard=1 \
          --listenport=8080 \
          --redishost=${Redis.PublicIp} \
          --redisport=6379

          service tyk-gateway start

      ImageId: ami-0ba0ce0c11eb723a1
      InstanceType: t2.micro
      SecurityGroupIds: 
        - !Ref ApplicationSG
      KeyName: !Ref KeyPairName
      Tags:
        - Key: "Name"
          Value: Gateway02 

#Create an Application Load Balancer
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: MyALB
      Subnets:
        - subnet-6ccb030a
        - subnet-33679e7b

#Create a Listener on Port 80
  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
      - Type: forward
        TargetGroupArn: !Ref ALBTargetGroup
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP


#Create a Target Group:
  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckPath: /hello
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 5
      HealthCheckTimeoutSeconds: 5
      HealthCheckIntervalSeconds: 10
      Matcher:
        HttpCode: 200
      Name: MyTargetGroup
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VpcName
      #TargetType: instance
      Targets:
        - Id: !Ref Gateway01
        - Id: !Ref Gateway02


